name: haskell

on:
  push:
    paths:
      - 'haskell/*'
      - .github/workflows/haskell.yml
    branches:
      - main
    tags:
      - v*.*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish caphosra/haskell

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            caphosra/haskell
            ghcr.io/caphosra/haskell
          tags: |
            latest

      - name: Generate the image file
        run: |
          python3 ./build.py ./haskell/haskell

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./haskell/haskell.gen.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            - UBUNTU_VERSION=20.04
